### ISSUE TITLE
Can you check this?

### ISSUE THREAD

**Issue by dr-mo27** [abitmore/btstools#1]
Hi @abitmore ,

I hope you've been well during quarantine.  I hope this doesn't interfere with anything you are working on, I tried to pick something older to put an issue on. I'm sure this is an unconventional way to try and reach you, but I work for Protocol Labs and we are currently hiring a Partner Engineer.  We are looking for back end engineers who are actively contributing to Open Source, and your GitHub looks like a potential fit.  I'll share my LinkedIn profile below so you can see I am a real recruiter working at Protocol Labs!  Please let me know if you are interested by sending me an email at davis.momii@protocol.ai.  

https://www.linkedin.com/in/davisrikitomomii/

**Comment by abitmore** [comment]
Thanks for the greetings. I'm fine. I'm now working on [BitShares](https://bitshares.org) and unavailable to be hired elsewhere anytime soon. For potential business cooperation please contact dbis@bitshares.org .
